### ISSUE TITLE
[BUG] upnext doesn't work with TMDB Player since TMDbHelper v6.7.4

### ISSUE THREAD

**Issue by nat80** [MoojMidge/service.upnext#49]
Hi,

I noticed that upnext doesn't works with the tmdb player since the TMDB Helper 6.7.4 update.

I enabled these two options:
- Enable TMDBHelper integration
- Enable full integration

I got this error : AttributeError: 'TMDb' object has no attribute 'get_tmdb_id'

Full logs here : https://paste.kodi.tv/vibedarudu.kodi

**Comment by MoojMidge** [comment]
Please stop requesting changes be made to TMDbHelper.

When this functionality was added, it was agreed that there was no public API being provided, and that the ability to import TBDbHelper as a module was provided as-is, with any changes required to make it work being the responsibility of whatever was using it, in this case UpNext.

Bug fixes for something like `Players.get_next_episodes` is one thing, but backwards compatibility shims for `TMDb.tmdb_api` and `TMDb.get_tmdb_id` and anything else should be fixed in UpNext rather than being patched within TMDbHelper, although jurialmunkey is free to do so at his discretion, if he has time.

It otherwise simply adds to the unpaid support workload required to maintain TMDbHelper, and I will sooner remove this functionality from UpNext than contribute to that.

Please be patient, I will fix the problems in UpNext shortly. In the meantime you can disable full TMDbHelper integration `UpNext > Settings > Expert > General > Enable TMDbHelper integration > Enable full integration`

**Comment by nat80** [comment]
I tried with full integration disabled.
I get the popup (without the poster), and when I click Play, I get this message:
Unable to play video
If it helps, here's the log:
https://paste.kodi.tv/ogotagujad.kodi

**Comment by nat80** [comment]
Hi,
I just tested, it's works with full integration disabled (so without poster) and when I select play, TMDB show me dialog with option to play with player or search with player insteed of play directly next episode as it was before.

With full integration enabled I got this error : 
> AttributeError: 'xbmcgui.ListItem' object has no attribute 'is_unaired'

logs : https://paste.kodi.tv/ibiticuleq.kodi

I'm available to test other changes if necessary, thanks !

**Comment by MoojMidge** [comment]
> with full integration disabled ... when I select play, TMDB show me dialog with option to play with player or search with player insteed of play directly next episode as it was before.

When you say "as it was before" do you mean using an older version of TMDbHelper and with full integration still disabled, or using an older version of TMDbHelper and full integration enabled? I think with full integration disabled the only way to avoid this is to also enable `Exact match only`.


> With full integration enabled I got this error :
> 
> > AttributeError: 'xbmcgui.ListItem' object has no attribute 'is_unaired'

Looks like the code in UpNext expects that the `tmdbhelper_lib.player.players.Player.get_next_episodes` method to returns a list of TMDbHelper listitems, but it is actually returning a list of Kodi listitems. However it looks like it always did this, but apparently it still worked, just not sure how.

Can you test whether it works with full integration enabled and using an older version of TMDbHelper?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v5.5.15

If it works there I'll take a closer look at what may have changed, to retain backwards compatibility, otherwise just try to update Upnext to suit what `tmdbhelper_lib.player.players.Player.get_next_episodes` currently does.

**Comment by MoojMidge** [comment]
Next try:
https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip

Good chance this still won't work properly, but if you can test some or all of the following and get a log should able to get it sorted:

- `Full integration` disabled
  - `Exact match only` disabled
  - `Exact match only` enabled
- `Full integration` enabled
  - `Queue all next episodes` disabled
  - `Queue all next episodes` enabled

**Comment by nat80** [comment]
With an older version of TMDB Helper like v5.5, upnext worked fine with only full integration option enabled.

Here the logs for all cases with the latest version of tmdb helper and upnext with your last commit :

- `Full integration` disabled
    - `Exact match only` disabled
         Works but without poster and selection of tmdb player is needed : https://paste.kodi.tv/oxejuxawot.kodi

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/e9d80f4e-27bf-4ba3-acb0-6c2662263743" />

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/efcc7570-3d2d-4af2-ba2f-7165f73dd385" />

-
    - `Exact match only` enabled
        AttributeError: 'PlayerNextEpisodes' object has no attribute 'lisitems' : https://paste.kodi.tv/uyutatuhul.kodi


- `Full integration` enabled
    - `Queue all next episodes` disabled
          AttributeError: 'PlayerNextEpisodes' object has no attribute 'lisitems' : https://paste.kodi.tv/vuyakuduje.kodi

    - `Queue all next episodes` enabled
	  AttributeError: 'PlayerNextEpisodes' object has no attribute 'lisitems' : https://paste.kodi.tv/usasufuliy.kodi

**Comment by jurialmunkey** [comment]
> Looks like the code in UpNext expects that the tmdbhelper_lib.player.players.Player.get_next_episodes method to returns a list of TMDbHelper listitems, but it is actually returning a list of Kodi listitems. However it looks like it always did this, so while apparently it used to work, I'm just not sure how.

@MoojMidge - Actually, I think it did return TMDbHelper listitems originally.

If it is going to make things easier for you for backwards compatibility, I can make this change relatively easily as it is not a big deal for me to convert these further along. I was 50/50 on what it was returning originally and didn't check close enough.

> AttributeError: 'PlayerNextEpisodes' object has no attribute 'lisitems' 

@nat80 This looks like a simple typo in MoojMidge's code here. 
https://github.com/MoojMidge/service.upnext/blob/b702a79b16d88e08bb7aa18a5a83d40198f1051c/resources/lib/tmdb_helper.py#L122

it should be `listitems` not `lisitems` - you can probably change that yourself to test it.

**Comment by nat80** [comment]
I tried with `listitems` with `Full integration` and `Queue all next episodes` enabled or disabled and now I have this error :
`AttributeError: 'xbmcgui.ListItem' object has no attribute 'format_unaired_label'`

log : https://paste.kodi.tv/udososagux.kodi

**Comment by MoojMidge** [comment]
@jurialmunkey 

> Actually, I think it did return TMDbHelper listitems originally.

Are you sure? I don't have a device to actually test with, but what is confusing me about the old code is that there were two `get_listitem` methods, one created a `ListItem` instance and the second was a method of that instance that created a `KodiListItem`.

However [`tmdbhelper.lib.player.putils.make_playlist`](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/61718f31d15669b8a23c410c93d7db6775453a86/resources/tmdbhelper/lib/player/putils.py#L1-L9) seems to expect Kodi listitems while [`tmdbhelper.lib.player.putils.make_upnext`](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/61718f31d15669b8a23c410c93d7db6775453a86/resources/tmdbhelper/lib/player/putils.py#L12-L19) expects TMDbHelper listitems, but they both use the [same collection of next episodes](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/61718f31d15669b8a23c410c93d7db6775453a86/resources/tmdbhelper/lib/player/players.py#L843-L848)

The old patching I used in this addon assumed TMDbHelper listitems, and while I am pretty certain it did work before, I am now second guessing myself.

> If it is going to make things easier for you for backwards compatibility, I can make this change relatively easily as it is not a big deal

The newer code is a lot clearer, so my 2c would be to just stick to whatever you need/want it to be and I can deal with the monkey patching in this addon. I have to do it anyway, and backwards compatibility is not a specific goal, so the old code will just remain as-is and the new code will match whatever TMDbHelper is doing now.

@nat80 - it was indeed a typo, but was meant to be `.items` not `.listitems`. Give https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip another go.

**Comment by jurialmunkey** [comment]
> The old patching I used in this addon assumed TMDbHelper listitems, and while I am pretty certain it did work before, I am now second guessing myself.

I think I was looking at the same when I updated it which is also why I was 50/50 on what it was returning originally.

> The newer code is a lot clearer, so my 2c would be to just stick to whatever you need/want it to be and I can deal with the monkey patching in this addon.

No worries. I'll leave as is in that case as I think in most scenarios the Kodi ListItem is more useful and expected. And, as you've discovered, you can easily get the TMDbHelper type ListItem from the `.items` attribute instead.

**Comment by nat80** [comment]
There are no more errors, but upnext can't find the next episode. I've tried all combinations of upnext options without success.
Each time, I get this message in the logs:
```
UpNextState -> Plugin next_video: None
UpNextPopupHandler -> Exiting: no next item to play
```
logs : https://paste.kodi.tv/usecagapox.kodi

**Comment by MoojMidge** [comment]
Made one minor change that doesn't really change anything, just prevents double-handling between UpNext and TMDbHelper.

Can you confirm there are still no errors with latest update?
https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip

> but upnext can't find the next episode
> ...
> Each time, I get this message in the logs:
> 
> ```
> UpNextState -> Plugin next_video: None
> UpNextPopupHandler -> Exiting: no next item to play
> ```

Everything seems to be working properly, but you have `UpNext > Settings > Behaviour > Next selection > Previously watched videos` disabled. As the next episode has already been watched UpNext has nothing to try and play.

Not sure how it would have worked previously with this setting disabled, ~~as the playcount is coming from Kodi and handling of this wouldn't have changed with any addon updates.~~ but the playcount for the next episodes may be a added bonus of the updates to TMDbHelper storing data from various sources eg Trakt and now properly combining them when responding to queries

**Comment by nat80** [comment]
I enabled the setting `Previously watched videos` (I don't know if I had enabled it with the previous version).
But everything works fine now, and with your latest change as well.
Thank you for your help and your work on this excellent addon.

**Comment by jurialmunkey** [comment]
> but the playcount for the next episodes may be a added bonus of the updates to TMDbHelper storing data from various sources eg Trakt and now properly combining them when responding to queries

Yep, this'd be it.

If the user has Trakt watched/progress sync enabled you should get the playcount/resume/episodecount etc. properties coming through on the ListItem that is generated.

**Comment by nat80** [comment]
After a few tests, I noticed that the nextup popup often doesn't display the next episode poster.
I don't know if this issue is related to upnext or tmdb helper, or if I should create another issue.

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/3ac879c4-3ec7-429c-a1b1-626b80b89da9" />
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/be006e56-22fc-4cc5-b392-1c5106df96ff" />

logs : https://paste.kodi.tv/lusexuriga.kodi

**Comment by MoojMidge** [comment]
The TMDb requests are failing with a HTTP 401 Unauthorized status. UpNext uses its own API key for making these requests through TMDbHelper, and the API key needs to replace what TMDbHelper uses internally as the internal API keys are for the specific use of TMDbHelper and not third party projects.

I noticed this in one of your previous logs but thought I had patched this correctly when you mentioned that it was now working. It may be that you were simply seeing data that TMDbHelper had previously cached, while uncached data needed to be requested and then subsequently fails to be fetched.

I'll have to have a look at where else the TMDb API is being used in order to correctly use the UpNext provided TMDb API key.

**Comment by nat80** [comment]
upnext isn't longer working since I got a new error with the last version of tmdb helper :
`AttributeError: '_Episode' object has no attribute 'format_unaired_label'`

logs: https://paste.kodi.tv/sewayusobi.kodi

**Comment by jurialmunkey** [comment]
> upnext isn't longer working since I got a new error with the last version of tmdb helper : `AttributeError: '_Episode' object has no attribute 'format_unaired_label'`
> 
> logs: https://paste.kodi.tv/sewayusobi.kodi

Yeah this method is removed. I'm assuming it was being used to check if the item has aired yet, in which case the `is_unaired` property can be used i.e.

```
if items[1].is_unaired:
```

**Comment by MoojMidge** [comment]
> Everything seems to be working properly, but you have `UpNext > Settings > Behaviour > Next selection > Previously watched videos` disabled. As the next episode has already been watched UpNext has nothing to try and play.

Updated so that this setting works in a similar way for plugin items using TMDbHelper as it does for Kodi library items - it will skip any watched videos and will only present a popup for the next unwatched video.



> I got a new error with the last version of tmdb helper :
> `AttributeError: '_Episode' object has no attribute 'format_unaired_label'`


> the `is_unaired` property can be used

Updated: https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip

Haven't had time to look at anything else.

**Comment by nat80** [comment]
Most of the time I don't have the poster for the next episode (because of 401 errors on tmdb api) but it works again.
Thanks.

**Comment by nat80** [comment]
Hello, I come back to this issue. I disabled Upnext because I can't use it due to the 401 errors that occur 90% of the time.
Fresh log here if you have the time to check: https://paste.kodi.tv/zufupiquro.kodi

**Comment by nat80** [comment]
I have a new error with upnext:
```
File "/Users/nathan/Library/Application Support/Kodi/addons/service.upnext/resources/lib/state.py", line 427, in _get_tmdb_now_playing
                                                       current_video = get_item_details(
                                                                       ^^^^^^^^^^^^^^^^^
                                                   TypeError: 'NoneType' object is not callable
                                                   -->End of Python script error report<--
```
full log: https://paste.kodi.tv/enanowepaj.kodi

**Comment by MoojMidge** [comment]
Yes, the player module structure is undergoing some changes beginning from v6.9.9 of TMDbHelper, with a larger refactor in the works from what I can see.

I'll add some extra checks to try to account for the changes but I think you should expect this to not work, or to intermittantly break until the internal API stabilises.

**Comment by jurialmunkey** [comment]
MoojMidge is of course correct.

Player functionality currently undergoing a refactor. It's not worth trying to chase the changes until it is done. Currently it is in a bit of a half-way incomplete state that temporarily broke a few functions.

Had intended to address these much earlier but unfortunately ended up extremely busy at work so haven't had as much time as I would like (and my work is what pays the bills!).

**Comment by nat80** [comment]
Hi, this issue has been pending for a while and I'm wondering if the refactoring of the TMDB Helper player functionality has been completed to take into account the new changes ?

**Comment by nat80** [comment]
I made a fork but I only tested with my setup, it's possible that not everything will work as intended. https://github.com/nat80/service.upnext
